CREATE TABLE usuarios (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Nombres VARCHAR(255) NOT NULL,
    Apellidos VARCHAR(255) NOT NULL,
    login VARCHAR(50) NOT NULL,
    pwd VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL
);
